1. Object x <-1:15 
Construct a 5x3 matrix for the value of x. 

In [1]:
x <- 1:15
matrix(x, nrow=5, ncol=3)

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8   13  
[4,] 4     9   14  
[5,] 5    10   15

2. Write a program to generate the following 4x4 matrix
0 0 0 0 
0 0 0 0 
0 0 0 0 

In [2]:
matrix(0, nrow=4, ncol=4)

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

3. The object x<-1:8 
Write a program to generate the following 3x8 matrix using "cbind(),rbind(),rev(),rep()" 
1 2 3 4 5 6 7 8 
8 7 6 5 4 3 2 1 
3 3 3 3 3 3 3 3 

In [3]:
x <- 1:8
rbind(unname(x), rev(x), rep(3,8))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3    4    5    6    7    8   
[2,] 8    7    6    5    4    3    2    1   
[3,] 3    3    3    3    3    3    3    3

4. Choose two different(x,y) 4x4 matrix to perform the following arithmetic operations (a). x + y 
(b). x - y 
(c). x*y 
(d). x%*%y 
(e). Difference between (c) &(d) 
-> The difference between (c) and (d) is that in (c) each element of x multiplies with each element of y, but in (d) it is a product of two matrices.
(f). Inverse of y 
(g). z<-x/y 
(h). Transpose of z 
(i). Diagonal of transpose matrix 

In [5]:
x <- matrix(0:15, nrow=4)
y <- matrix(1:16, nrow=4)

# x + y
x + y

# x - y
x - y

# x * y
x * y 

# x %*% y
x %*% y

# Inverse of y
library(MASS)
ginv(y)

# z <- x / y
z <- x / y
z

# Transpose of z
t <- t(z)
t

# Diagonal of Transpose Matrix
diag(t)

[,1] [,2] [,3] [,4]
[1,] 1     9   17   25  
[2,] 3    11   19   27  
[3,] 5    13   21   29  
[4,] 7    15   23   31

[,1] [,2] [,3] [,4]
[1,] -1   -1   -1   -1  
[2,] -1   -1   -1   -1  
[3,] -1   -1   -1   -1  
[4,] -1   -1   -1   -1

[,1] [,2] [,3] [,4]
[1,]  0   20    72  156 
[2,]  2   30    90  182 
[3,]  6   42   110  210 
[4,] 12   56   132  240

[,1] [,2] [,3] [,4]
[1,]  80  176  272  368 
[2,]  90  202  314  426 
[3,] 100  228  356  484 
[4,] 110  254  398  542

[,1]   [,2]    [,3]  [,4]   
[1,] -0.285 -0.1075  0.07  0.2475
[2,] -0.145 -0.0525  0.04  0.1325
[3,] -0.005  0.0025  0.01  0.0175
[4,]  0.135  0.0575 -0.02 -0.0975

[,1]      [,2]      [,3]      [,4]     
[1,] 0.0000000 0.8000000 0.8888889 0.9230769
[2,] 0.5000000 0.8333333 0.9000000 0.9285714
[3,] 0.6666667 0.8571429 0.9090909 0.9333333
[4,] 0.7500000 0.8750000 0.9166667 0.9375000

[,1]      [,2]      [,3]      [,4]     
[1,] 0.0000000 0.5000000 0.6666667 0.7500000
[2,] 0.8000000 0.8333333 0.8571429 0.8750000
[3,] 0.8888889 0.9000000 0.9090909 0.9166667
[4,] 0.9230769 0.9285714 0.9333333 0.9375000

[1] 0.0000000 0.8333333 0.9090909 0.9375000

5. Difference between (i) & (ii) 
(i). x<-matrix(x<-1:9,3,3,byrow = TRUE) (ii). x<-matrix(x<-1:9,3,3) 
(i) is created by filling the value from vector by row first
(ii) is created by filling the value from vector by col first

6. Which function can we use for inner product and outer product in matrix calculation? 
-> The function that we can use for inner product is %*%.
-> The function that we can use for outer product is %o%.

7. Explain the use of all.equal() function in Matrix with a sample program. 
-> The use of all.equal() function is to compare whether 2 matrices are equal or nearly equal or not, and it will return the mean of the differences.

In [6]:
x <- matrix(0:15, nrow=4)
y <- matrix(1:16, nrow=4)
all.equal(x,y)

[1] "Mean relative difference: 0.1333333"

8. Explain the use of dim() function with a sample program. 
-> The use of dim() function is to find the dimension of a matrix. It will return 2 integer, the first integer is the row, and the second integer is the column.

In [7]:
x <- matrix(0:15, nrow=4)
dim(x)

[1] 4 4

9. Use of $ operator, and square brackets [] in List with example program. 
-> The use of $ operator is to access the element in a list by using name.
-> The use of [] operator is to access the element in a list by using index.

In [9]:
a <- list(school="KIT", major="Software Engineering", year=4, batch=4)
a$school
a[2]

[1] "KIT"

$major
[1] "Software Engineering"

10. Explain ifelse() with example. 
->ifelse() is used to check whether a statement is true or false based on the given condition, and perform any operation accordingly.

In [10]:
num <- 2
ifelse(num %% 2 == 0, "even", "odd")

[1] "even"

11. Write a program to get the weight and height from the user to calculate the following cases a. If your BMI is less than 18.5, it falls within the underweight range. 
b. If your BMI is 18.5 to <25, it falls within the normal. 
c. If your BMI is 25.0 to <30, it falls within the overweight range. 
d. If your BMI is 30.0 or higher, it falls within the obese range. 

In [11]:
weight <- as.numeric(readline(prompt="Enter weight(kg): "))
height <- as.numeric(readline(prompt="Enter height(m): "))
bmi <- weight/(height^2)
if(bmi<18.5){
    "underweight"
}else if (bmi<25) {
    "normal"
}else if (bmi<30) {
    "overweight"
}else{
    "obese"
}

Enter weight(kg): 61
Enter height(m): 1.73


[1] "normal"

12. Difference between List and Data frame with an example program. 
-> List accepts element of same or different data types and is stored in sequence.
-> Data frame is the list of same or different data types that is stored in the form of rows and columns

In [12]:
# List
list(1, "Song Sokha Vudthi", "Student", "Accounting", TRUE)

# Data Frame
batch <- c( 1, 2, 3, 4)
year <- c( 4, 3, 2, 1)
data.frame(Batch = batch, Year = year)

[[1]]
[1] 1

[[2]]
[1] "Song Sokha Vudthi"

[[3]]
[1] "Student"

[[4]]
[1] "Accounting"

[[5]]
[1] TRUE

Batch Year
1 1     4   
2 2     3   
3 3     2   
4 4     1

13. Difference between repeat and while loop with example program. 
-> Repeat requires you to explicitly break the loop by yourself, can be at any point in the loop.
-> While will break the loop when the condition is no longer true.

In [14]:
"Repeat"
i <- 5
repeat {if (i==0) break; print(i);i<-i-1}

"While"
i <- 5
while (i!=3) {print(i);i<-i-1}

[1] "Repeat"

[1] 5
[1] 4
[1] 3
[1] 2
[1] 1


[1] "While"

[1] 5
[1] 4
